### ISSUE TITLE
Questions about eval the result

### ISSUE THREAD

**Issue by Ju-Wenhao** [Jamson-Zhong/Graph2Edits#9]
When I try to run: python eval.py --dataset uspto_50k --experiments 27-06-2022--10-27-22
the process continued, but it can't show the result about eval, it shows at every line: Exception while final mol to Smiles: 'NoneType' object has no attribute 'GetAtoms', 
could you help me solve this problem? thanks.
![image](https://github.com/Jamson-Zhong/Graph2Edits/assets/104217357/a8aa0f9c-1ebc-4f96-b813-4af3f75bdba3)
![image](https://github.com/Jamson-Zhong/Graph2Edits/assets/104217357/0061072e-2a9f-46a8-9d36-a005827200f7)

**Comment by MianchuWang** [comment]
Hi Wenhao. Do you know the reason of this exception finally?
